// AI前沿知识题库 - 200道题
// 涵盖：大模型、AI应用、机器学习、深度学习、AI伦理、物联网AI、AI工具等

export const QUIZ_QUESTIONS_200 = [
  // ===== 大语言模型（LLM）=====
  {
    question: "GPT系列模型中，GPT代表什么？",
    optionA: "General Purpose Transformer",
    optionB: "Generative Pre-trained Transformer",
    optionC: "Guided Processing Technology",
    optionD: "Global Pattern Training",
    correctAnswer: "B" as const,
    explanation: "GPT全称Generative Pre-trained Transformer，即生成式预训练Transformer模型，由OpenAI开发。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪个模型是由Meta（Facebook）开发的开源大语言模型？",
    optionA: "GPT-4",
    optionB: "Claude",
    optionC: "LLaMA",
    optionD: "Gemini",
    correctAnswer: "C" as const,
    explanation: "LLaMA（Large Language Model Meta AI）是Meta开发的开源大语言模型系列，对学术研究和商业应用都产生了深远影响。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Transformer架构中的'注意力机制'（Attention）的核心作用是什么？",
    optionA: "加速模型训练速度",
    optionB: "让模型关注输入序列中不同位置的相关性",
    optionC: "减少模型参数数量",
    optionD: "提高图像识别精度",
    correctAnswer: "B" as const,
    explanation: "注意力机制让模型在处理每个词时，能够动态关注输入序列中其他位置的词，捕捉长距离依赖关系。",
    reward: 5,
    isActive: true,
  },
  {
    question: "大语言模型中的'幻觉'（Hallucination）是指什么？",
    optionA: "模型运行速度过慢",
    optionB: "模型生成听起来合理但实际错误的内容",
    optionC: "模型无法理解图像",
    optionD: "模型占用内存过多",
    correctAnswer: "B" as const,
    explanation: "AI幻觉指模型自信地生成看似合理但实际上不准确或虚构的信息，是当前大模型的主要挑战之一。",
    reward: 5,
    isActive: true,
  },
  {
    question: "RAG（检索增强生成）技术的主要目的是什么？",
    optionA: "提高模型的图像生成质量",
    optionB: "让模型能够访问外部知识库，减少幻觉",
    optionC: "加速模型推理速度",
    optionD: "降低模型训练成本",
    correctAnswer: "B" as const,
    explanation: "RAG（Retrieval-Augmented Generation）通过在生成前先检索相关文档，将外部知识注入模型，有效减少幻觉并提高回答准确性。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪个不是主流的大语言模型？",
    optionA: "Claude（Anthropic）",
    optionB: "Gemini（Google）",
    optionC: "AlphaGo（DeepMind）",
    optionD: "文心一言（百度）",
    correctAnswer: "C" as const,
    explanation: "AlphaGo是DeepMind开发的围棋AI，不是大语言模型。Claude、Gemini、文心一言都是大语言模型。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Prompt Engineering（提示词工程）的主要目标是什么？",
    optionA: "训练新的AI模型",
    optionB: "通过优化输入提示词来获得更好的AI输出结果",
    optionC: "修复AI模型的代码错误",
    optionD: "减少AI模型的参数量",
    correctAnswer: "B" as const,
    explanation: "提示词工程是通过精心设计输入提示词（Prompt）来引导AI模型产生更准确、更有用输出的技术和方法论。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Chain-of-Thought（思维链）提示技术的作用是什么？",
    optionA: "让AI生成更长的文章",
    optionB: "引导AI逐步推理，提高复杂问题的解决能力",
    optionC: "加快AI的响应速度",
    optionD: "让AI记住更多对话历史",
    correctAnswer: "B" as const,
    explanation: "思维链（CoT）提示通过要求模型'一步步思考'，显著提升了模型在数学推理、逻辑推断等复杂任务上的表现。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Fine-tuning（微调）与Prompt Engineering的主要区别是什么？",
    optionA: "微调需要修改模型权重，提示词工程不需要",
    optionB: "微调只能用于图像模型",
    optionC: "提示词工程需要更多数据",
    optionD: "两者完全相同",
    correctAnswer: "A" as const,
    explanation: "微调通过在特定数据集上继续训练来更新模型权重；提示词工程则是在不改变模型参数的情况下，通过设计输入来优化输出。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Token在大语言模型中是什么？",
    optionA: "模型的访问密钥",
    optionB: "文本的基本处理单元，可以是单词或字符片段",
    optionC: "模型的训练轮次",
    optionD: "神经网络的层数",
    correctAnswer: "B" as const,
    explanation: "Token是LLM处理文本的基本单位，通常是词或子词。GPT-4的上下文窗口以Token数量衡量，1000个英文单词约1300个Token。",
    reward: 5,
    isActive: true,
  },

  // ===== 机器学习基础 =====
  {
    question: "监督学习（Supervised Learning）的特点是什么？",
    optionA: "不需要任何训练数据",
    optionB: "使用带有标签的训练数据",
    optionC: "只能处理图像数据",
    optionD: "模型自动发现数据中的隐藏结构",
    correctAnswer: "B" as const,
    explanation: "监督学习使用带有正确答案（标签）的训练数据，模型通过学习输入与输出的对应关系来做出预测。",
    reward: 5,
    isActive: true,
  },
  {
    question: "过拟合（Overfitting）是指什么？",
    optionA: "模型训练速度太慢",
    optionB: "模型在训练集上表现好但在新数据上表现差",
    optionC: "模型参数太少",
    optionD: "训练数据量不足",
    correctAnswer: "B" as const,
    explanation: "过拟合指模型过度学习了训练数据的噪声和细节，导致泛化能力差，在未见过的数据上表现不佳。",
    reward: 5,
    isActive: true,
  },
  {
    question: "梯度下降（Gradient Descent）在机器学习中的作用是什么？",
    optionA: "数据预处理",
    optionB: "通过迭代更新参数来最小化损失函数",
    optionC: "数据可视化",
    optionD: "模型部署",
    correctAnswer: "B" as const,
    explanation: "梯度下降是最常用的优化算法，通过计算损失函数对参数的梯度，沿梯度反方向更新参数，逐步找到最优解。",
    reward: 5,
    isActive: true,
  },
  {
    question: "强化学习（Reinforcement Learning）中，智能体通过什么来学习？",
    optionA: "大量标注数据",
    optionB: "与环境交互获得奖励或惩罚",
    optionC: "无监督聚类",
    optionD: "人工编写的规则",
    correctAnswer: "B" as const,
    explanation: "强化学习中，智能体通过与环境交互，根据获得的奖励（正反馈）或惩罚（负反馈）来学习最优策略。",
    reward: 5,
    isActive: true,
  },
  {
    question: "RLHF（基于人类反馈的强化学习）在大模型中的作用是什么？",
    optionA: "加速模型训练",
    optionB: "让模型输出更符合人类价值观和偏好",
    optionC: "减少模型参数",
    optionD: "提高图像生成质量",
    correctAnswer: "B" as const,
    explanation: "RLHF通过收集人类对模型输出的评分，训练奖励模型，再用强化学习优化语言模型，使其输出更安全、有用、符合人类偏好。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪种算法属于无监督学习？",
    optionA: "线性回归",
    optionB: "支持向量机（SVM）",
    optionC: "K-means聚类",
    optionD: "随机森林",
    correctAnswer: "C" as const,
    explanation: "K-means是无监督学习算法，不需要标签，通过计算数据点间距离将数据自动分成K个簇。",
    reward: 5,
    isActive: true,
  },
  {
    question: "迁移学习（Transfer Learning）的核心思想是什么？",
    optionA: "将数据从一台机器转移到另一台",
    optionB: "将在一个任务上学到的知识应用到新任务",
    optionC: "将模型从云端迁移到本地",
    optionD: "将大模型压缩为小模型",
    correctAnswer: "B" as const,
    explanation: "迁移学习利用在大规模数据上预训练的模型，通过少量数据微调来解决新任务，大幅降低训练成本。",
    reward: 5,
    isActive: true,
  },
  {
    question: "数据增强（Data Augmentation）在深度学习中的主要目的是什么？",
    optionA: "增加模型层数",
    optionB: "通过变换现有数据来扩充训练集，防止过拟合",
    optionC: "加速GPU计算",
    optionD: "减少模型参数",
    correctAnswer: "B" as const,
    explanation: "数据增强通过对原始数据进行翻转、旋转、裁剪、色彩变换等操作，人工扩充训练集，提高模型泛化能力。",
    reward: 5,
    isActive: true,
  },
  {
    question: "批归一化（Batch Normalization）的主要作用是什么？",
    optionA: "增加网络深度",
    optionB: "加速训练收敛，减少对初始化的敏感性",
    optionC: "减少训练数据需求",
    optionD: "提高模型可解释性",
    correctAnswer: "B" as const,
    explanation: "批归一化通过对每个mini-batch的激活值进行标准化，稳定训练过程，加速收敛，并有一定正则化效果。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Dropout技术在神经网络中的作用是什么？",
    optionA: "提高模型推理速度",
    optionB: "随机丢弃神经元，防止过拟合",
    optionC: "减少训练时间",
    optionD: "增加模型容量",
    correctAnswer: "B" as const,
    explanation: "Dropout在训练时随机将部分神经元的输出置为0，迫使网络学习更鲁棒的特征表示，是常用的正则化技术。",
    reward: 5,
    isActive: true,
  },

  // ===== 深度学习与神经网络 =====
  {
    question: "卷积神经网络（CNN）最擅长处理哪类数据？",
    optionA: "时间序列数据",
    optionB: "图像和视频数据",
    optionC: "表格数据",
    optionD: "文本数据",
    correctAnswer: "B" as const,
    explanation: "CNN通过卷积层提取局部特征，利用权重共享和平移不变性，在图像识别、目标检测等视觉任务上表现卓越。",
    reward: 5,
    isActive: true,
  },
  {
    question: "循环神经网络（RNN）相比普通神经网络的主要优势是什么？",
    optionA: "计算速度更快",
    optionB: "能够处理序列数据，保留历史信息",
    optionC: "参数更少",
    optionD: "更容易训练",
    correctAnswer: "B" as const,
    explanation: "RNN通过循环连接保留序列中的历史信息，适合处理时间序列、文本等序列数据，但存在梯度消失问题。",
    reward: 5,
    isActive: true,
  },
  {
    question: "LSTM（长短期记忆网络）解决了RNN的什么问题？",
    optionA: "计算复杂度过高",
    optionB: "梯度消失/爆炸问题",
    optionC: "无法处理图像",
    optionD: "参数过多",
    correctAnswer: "B" as const,
    explanation: "LSTM通过门控机制（输入门、遗忘门、输出门）有效缓解了RNN的梯度消失问题，能够学习长距离依赖关系。",
    reward: 5,
    isActive: true,
  },
  {
    question: "生成对抗网络（GAN）由哪两个部分组成？",
    optionA: "编码器和解码器",
    optionB: "生成器和判别器",
    optionC: "特征提取器和分类器",
    optionD: "训练器和测试器",
    correctAnswer: "B" as const,
    explanation: "GAN由生成器（Generator）和判别器（Discriminator）组成，两者相互对抗：生成器生成假数据，判别器区分真假，共同进化。",
    reward: 5,
    isActive: true,
  },
  {
    question: "自编码器（Autoencoder）的主要用途是什么？",
    optionA: "文本翻译",
    optionB: "数据压缩、降维和特征学习",
    optionC: "目标检测",
    optionD: "语音识别",
    correctAnswer: "B" as const,
    explanation: "自编码器通过编码器将数据压缩到低维表示，再通过解码器重建，用于降维、特征提取、异常检测等任务。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Transformer中的'多头注意力'（Multi-Head Attention）有什么优势？",
    optionA: "减少计算量",
    optionB: "从不同角度捕捉序列中的多种依赖关系",
    optionC: "增加模型深度",
    optionD: "提高训练速度",
    correctAnswer: "B" as const,
    explanation: "多头注意力将注意力机制并行运行多次，每个'头'学习不同的注意力模式，使模型能同时关注序列的不同方面。",
    reward: 5,
    isActive: true,
  },
  {
    question: "位置编码（Positional Encoding）在Transformer中的作用是什么？",
    optionA: "压缩输入数据",
    optionB: "为序列中每个位置提供位置信息，因为注意力机制本身不感知顺序",
    optionC: "加速矩阵运算",
    optionD: "减少内存占用",
    correctAnswer: "B" as const,
    explanation: "Transformer的注意力机制本身不区分位置，位置编码通过为每个位置添加独特的编码，让模型感知词序信息。",
    reward: 5,
    isActive: true,
  },
  {
    question: "扩散模型（Diffusion Model）的工作原理是什么？",
    optionA: "通过对抗训练生成图像",
    optionB: "逐步向数据添加噪声，再学习逆向去噪过程",
    optionC: "通过变分推断生成数据",
    optionD: "直接映射随机噪声到图像",
    correctAnswer: "B" as const,
    explanation: "扩散模型先通过前向过程逐步向数据添加高斯噪声，再训练神经网络学习逆向去噪过程，从纯噪声生成高质量图像。Stable Diffusion即基于此原理。",
    reward: 5,
    isActive: true,
  },
  {
    question: "模型量化（Quantization）的主要目的是什么？",
    optionA: "提高模型精度",
    optionB: "减少模型大小和推理计算量，便于部署",
    optionC: "增加训练数据",
    optionD: "提高模型可解释性",
    correctAnswer: "B" as const,
    explanation: "量化将模型权重从高精度浮点数（如FP32）转换为低精度（如INT8、INT4），大幅减小模型体积和推理延迟，是边缘部署的关键技术。",
    reward: 5,
    isActive: true,
  },
  {
    question: "知识蒸馏（Knowledge Distillation）技术的目的是什么？",
    optionA: "从互联网提取知识",
    optionB: "用大模型（教师）指导小模型（学生）训练，保留性能的同时减小模型",
    optionC: "将多个模型合并为一个",
    optionD: "提高模型训练速度",
    correctAnswer: "B" as const,
    explanation: "知识蒸馏让小模型（学生）学习大模型（教师）的软标签输出，而非硬标签，从而在较小的模型尺寸下保留更多性能。",
    reward: 5,
    isActive: true,
  },

  // ===== AI应用与工具 =====
  {
    question: "以下哪个是AI代码辅助工具？",
    optionA: "Photoshop",
    optionB: "GitHub Copilot",
    optionC: "Excel",
    optionD: "Zoom",
    correctAnswer: "B" as const,
    explanation: "GitHub Copilot是由GitHub和OpenAI合作开发的AI代码辅助工具，能够根据注释和上下文自动生成代码。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Stable Diffusion是什么类型的AI模型？",
    optionA: "文本生成模型",
    optionB: "文本转图像生成模型",
    optionC: "语音识别模型",
    optionD: "视频分析模型",
    correctAnswer: "B" as const,
    explanation: "Stable Diffusion是开源的文本转图像扩散模型，用户输入文字描述即可生成高质量图像，已成为AI创作的重要工具。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI Agent（智能体）与普通AI聊天机器人的主要区别是什么？",
    optionA: "Agent响应速度更快",
    optionB: "Agent能够自主规划并执行多步骤任务，调用工具完成目标",
    optionC: "Agent只能回答问题",
    optionD: "Agent不需要训练",
    correctAnswer: "B" as const,
    explanation: "AI Agent能够自主分解目标、规划步骤、调用外部工具（搜索、代码执行、API等），完成需要多步骤推理的复杂任务。",
    reward: 5,
    isActive: true,
  },
  {
    question: "向量数据库（Vector Database）在AI应用中的主要用途是什么？",
    optionA: "存储视频文件",
    optionB: "高效存储和检索文本/图像的向量嵌入，用于语义搜索",
    optionC: "训练深度学习模型",
    optionD: "管理用户权限",
    correctAnswer: "B" as const,
    explanation: "向量数据库（如Pinecone、Weaviate、Milvus）专门存储高维向量，支持快速近似最近邻搜索，是RAG和语义搜索的核心基础设施。",
    reward: 5,
    isActive: true,
  },
  {
    question: "LangChain框架的主要功能是什么？",
    optionA: "训练大语言模型",
    optionB: "简化基于LLM的应用开发，提供链式调用和工具集成",
    optionC: "部署AI模型到云端",
    optionD: "数据标注工具",
    correctAnswer: "B" as const,
    explanation: "LangChain是开源框架，提供链式调用、记忆管理、工具集成、Agent构建等功能，大幅简化了基于大语言模型的应用开发。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Midjourney和DALL-E主要用于什么？",
    optionA: "代码生成",
    optionB: "AI图像生成",
    optionC: "语音合成",
    optionD: "数据分析",
    correctAnswer: "B" as const,
    explanation: "Midjourney和DALL-E都是AI图像生成工具，用户输入文字描述即可生成艺术图像，已在设计、创意等领域广泛应用。",
    reward: 5,
    isActive: true,
  },
  {
    question: "语音克隆（Voice Cloning）技术的主要风险是什么？",
    optionA: "音质太差",
    optionB: "被用于深度伪造（Deepfake）欺诈和诈骗",
    optionC: "计算成本太高",
    optionD: "只能克隆英语",
    correctAnswer: "B" as const,
    explanation: "语音克隆技术可以用极少量样本复制任何人的声音，存在被用于电话诈骗、身份冒充等严重安全风险，需要加强监管。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI在医疗领域的典型应用不包括以下哪项？",
    optionA: "医学影像辅助诊断",
    optionB: "药物研发加速",
    optionC: "手术机器人辅助",
    optionD: "替代医生做所有诊断决策",
    correctAnswer: "D" as const,
    explanation: "AI在医疗领域是辅助工具，不能完全替代医生的临床判断。医疗AI的定位是辅助诊断、提高效率，最终决策仍需医生负责。",
    reward: 5,
    isActive: true,
  },
  {
    question: "自动驾驶汽车中，LiDAR（激光雷达）的主要作用是什么？",
    optionA: "提供车内娱乐",
    optionB: "通过发射激光脉冲精确测量周围环境的3D距离信息",
    optionC: "连接互联网",
    optionD: "控制车辆速度",
    correctAnswer: "B" as const,
    explanation: "LiDAR通过发射激光并测量反射时间，生成高精度3D点云地图，是自动驾驶感知系统的核心传感器之一。",
    reward: 5,
    isActive: true,
  },
  {
    question: "推荐系统中，协同过滤（Collaborative Filtering）的工作原理是什么？",
    optionA: "分析商品的内容特征",
    optionB: "基于用户行为相似性，向用户推荐相似用户喜欢的内容",
    optionC: "随机推荐热门内容",
    optionD: "只推荐用户历史购买过的商品",
    correctAnswer: "B" as const,
    explanation: "协同过滤通过找到行为相似的用户群体，基于'相似用户喜欢的内容你也可能喜欢'的逻辑进行推荐，是Netflix、Amazon等平台的核心算法。",
    reward: 5,
    isActive: true,
  },

  // ===== AI伦理与安全 =====
  {
    question: "AI偏见（AI Bias）通常来源于什么？",
    optionA: "计算机硬件故障",
    optionB: "训练数据中存在的历史偏见和不平衡",
    optionC: "模型参数过多",
    optionD: "网络连接问题",
    correctAnswer: "B" as const,
    explanation: "AI偏见主要来源于训练数据中反映的历史歧视、数据不均衡等问题，可能导致模型对特定群体产生不公平的预测结果。",
    reward: 5,
    isActive: true,
  },
  {
    question: "可解释AI（Explainable AI，XAI）的主要目标是什么？",
    optionA: "让AI运行更快",
    optionB: "让AI的决策过程透明可理解，便于人类审查和信任",
    optionC: "减少AI的能耗",
    optionD: "提高AI的准确率",
    correctAnswer: "B" as const,
    explanation: "可解释AI旨在让AI系统的决策过程透明化，使用户、监管者能够理解AI为何做出特定决策，在医疗、金融、法律等高风险领域尤为重要。",
    reward: 5,
    isActive: true,
  },
  {
    question: "深度伪造（Deepfake）技术的主要危害是什么？",
    optionA: "占用大量存储空间",
    optionB: "可用于制造虚假视频/音频，传播虚假信息和实施诈骗",
    optionC: "降低视频质量",
    optionD: "增加网络延迟",
    correctAnswer: "B" as const,
    explanation: "Deepfake可以合成以假乱真的视频和音频，被用于政治操纵、名誉损害、金融诈骗等，是当前AI安全的重大挑战。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI对齐（AI Alignment）研究的核心问题是什么？",
    optionA: "如何让AI运行更快",
    optionB: "如何确保AI系统的目标和行为与人类价值观保持一致",
    optionC: "如何减少AI的能耗",
    optionD: "如何提高AI的准确率",
    correctAnswer: "B" as const,
    explanation: "AI对齐研究如何确保AI系统真正理解并遵循人类意图和价值观，防止AI在追求目标时产生有害的副作用，是AI安全领域的核心课题。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪项是AI治理的重要原则？",
    optionA: "AI应该完全自主，不受任何限制",
    optionB: "AI系统应该透明、公平、可问责",
    optionC: "AI决策不需要人类监督",
    optionD: "AI数据越多越好，无需考虑隐私",
    correctAnswer: "B" as const,
    explanation: "负责任的AI治理要求系统具备透明性（可解释）、公平性（无歧视）、可问责性（有责任主体）、安全性和隐私保护等核心原则。",
    reward: 5,
    isActive: true,
  },

  // ===== 物联网与AI =====
  {
    question: "边缘计算（Edge Computing）在IoT+AI中的主要优势是什么？",
    optionA: "降低硬件成本",
    optionB: "在数据产生的本地进行处理，降低延迟和带宽需求",
    optionC: "提高云服务器性能",
    optionD: "增加数据存储量",
    correctAnswer: "B" as const,
    explanation: "边缘计算将AI推理部署在靠近数据源的设备上，避免将所有数据传输到云端，大幅降低延迟（从秒级到毫秒级），适合实时控制场景。",
    reward: 5,
    isActive: true,
  },
  {
    question: "TinyML是什么？",
    optionA: "一种编程语言",
    optionB: "在微控制器等极低功耗设备上运行机器学习模型的技术",
    optionC: "一种数据库系统",
    optionD: "一种网络协议",
    correctAnswer: "B" as const,
    explanation: "TinyML是将机器学习模型部署到微控制器（如Arduino、STM32）等资源极度受限设备上的技术，实现毫瓦级功耗的智能推理。",
    reward: 5,
    isActive: true,
  },
  {
    question: "预测性维护（Predictive Maintenance）中AI的主要作用是什么？",
    optionA: "自动修复设备故障",
    optionB: "通过分析传感器数据预测设备何时可能发生故障",
    optionC: "降低设备购买成本",
    optionD: "替代维修工程师",
    correctAnswer: "B" as const,
    explanation: "AI通过分析振动、温度、电流等传感器数据，识别设备劣化模式，提前预测故障，实现从'定期维修'到'按需维修'的转变，大幅降低停机损失。",
    reward: 5,
    isActive: true,
  },
  {
    question: "数字孪生（Digital Twin）与AI结合的主要应用场景是什么？",
    optionA: "社交媒体管理",
    optionB: "实时模拟物理系统，优化运营和预测故障",
    optionC: "在线购物推荐",
    optionD: "游戏开发",
    correctAnswer: "B" as const,
    explanation: "数字孪生创建物理系统的虚拟副本，结合AI可以实时监控状态、模拟不同场景、优化运营参数，在智能制造、智慧城市等领域广泛应用。",
    reward: 5,
    isActive: true,
  },
  {
    question: "工业AI（Industrial AI）中，异常检测的典型方法是什么？",
    optionA: "人工逐一检查每个数据点",
    optionB: "训练模型学习正常模式，将偏离正常的数据标记为异常",
    optionC: "随机抽样检查",
    optionD: "只检查最新的数据",
    correctAnswer: "B" as const,
    explanation: "工业AI异常检测通常使用无监督或半监督方法，让模型学习设备正常运行时的数据分布，当新数据偏离正常范围时触发告警。",
    reward: 5,
    isActive: true,
  },

  // ===== 自然语言处理 =====
  {
    question: "词向量（Word Embedding）技术的作用是什么？",
    optionA: "将单词转换为图像",
    optionB: "将单词映射为稠密的数值向量，捕捉语义关系",
    optionC: "统计单词出现频率",
    optionD: "翻译不同语言",
    correctAnswer: "B" as const,
    explanation: "词向量（如Word2Vec、GloVe）将单词映射到高维向量空间，语义相近的词在空间中距离更近，是NLP的基础技术。",
    reward: 5,
    isActive: true,
  },
  {
    question: "命名实体识别（NER）在NLP中的任务是什么？",
    optionA: "生成新的文本",
    optionB: "识别文本中的人名、地名、组织名等特定实体",
    optionC: "翻译文本",
    optionD: "分析文本情感",
    correctAnswer: "B" as const,
    explanation: "NER是NLP的基础任务，自动识别并分类文本中的命名实体（人名、地名、机构名、日期等），广泛用于信息提取和知识图谱构建。",
    reward: 5,
    isActive: true,
  },
  {
    question: "情感分析（Sentiment Analysis）的主要应用场景不包括哪项？",
    optionA: "分析用户评论的正负面情绪",
    optionB: "监控社交媒体舆情",
    optionC: "自动驾驶路径规划",
    optionD: "品牌声誉管理",
    correctAnswer: "C" as const,
    explanation: "情感分析用于分析文本中的情感倾向，主要应用于用户评论分析、舆情监控、品牌管理等场景，与自动驾驶无关。",
    reward: 5,
    isActive: true,
  },
  {
    question: "机器翻译中，神经机器翻译（NMT）相比统计机器翻译（SMT）的主要优势是什么？",
    optionA: "翻译速度更快",
    optionB: "能够学习更复杂的语言模式，翻译更流畅自然",
    optionC: "不需要训练数据",
    optionD: "只能翻译短句",
    correctAnswer: "B" as const,
    explanation: "NMT使用端到端神经网络，能够学习更复杂的语言规律和上下文信息，生成更流畅自然的翻译，已成为Google翻译等主流系统的基础。",
    reward: 5,
    isActive: true,
  },
  {
    question: "文本摘要（Text Summarization）分为哪两种主要类型？",
    optionA: "快速摘要和慢速摘要",
    optionB: "抽取式摘要（从原文提取句子）和生成式摘要（生成新句子）",
    optionC: "中文摘要和英文摘要",
    optionD: "短摘要和长摘要",
    correctAnswer: "B" as const,
    explanation: "抽取式摘要从原文中选取关键句子组合；生成式摘要则像人类一样理解内容后用新语言表达，大语言模型擅长生成式摘要。",
    reward: 5,
    isActive: true,
  },

  // ===== 计算机视觉 =====
  {
    question: "目标检测（Object Detection）与图像分类的主要区别是什么？",
    optionA: "目标检测只能识别一个物体",
    optionB: "目标检测不仅识别物体类别，还定位物体在图像中的位置",
    optionC: "图像分类更难",
    optionD: "两者完全相同",
    correctAnswer: "B" as const,
    explanation: "图像分类只判断图像属于哪个类别；目标检测还需要用边界框（Bounding Box）标出每个物体的位置，是更复杂的任务。",
    reward: 5,
    isActive: true,
  },
  {
    question: "语义分割（Semantic Segmentation）的任务是什么？",
    optionA: "识别图像中的主要物体",
    optionB: "对图像中每个像素进行分类，标注其所属类别",
    optionC: "检测图像中的文字",
    optionD: "估计图像中物体的深度",
    correctAnswer: "B" as const,
    explanation: "语义分割对图像的每个像素进行分类（如天空、道路、人、车等），在自动驾驶、医学影像分析等场景中有重要应用。",
    reward: 5,
    isActive: true,
  },
  {
    question: "人脸识别技术的主要工作流程是什么？",
    optionA: "直接比较两张照片的像素",
    optionB: "人脸检测→特征提取→特征比对",
    optionC: "通过姓名数据库匹配",
    optionD: "分析发型和肤色",
    correctAnswer: "B" as const,
    explanation: "人脸识别通常分三步：先检测图像中的人脸位置，再提取人脸特征向量，最后与数据库中的特征向量比对计算相似度。",
    reward: 5,
    isActive: true,
  },
  {
    question: "OCR（光学字符识别）技术的主要应用是什么？",
    optionA: "生成艺术图像",
    optionB: "将图像中的文字转换为可编辑的数字文本",
    optionC: "识别图像中的人脸",
    optionD: "分析图像颜色",
    correctAnswer: "B" as const,
    explanation: "OCR将扫描文档、照片中的文字识别为可编辑文本，广泛应用于文档数字化、票据识别、车牌识别等场景。",
    reward: 5,
    isActive: true,
  },
  {
    question: "姿态估计（Pose Estimation）技术可以做什么？",
    optionA: "估计图像的拍摄时间",
    optionB: "检测人体关键点位置，分析人体姿态和动作",
    optionC: "识别图像中的文字",
    optionD: "估计图像的地理位置",
    correctAnswer: "B" as const,
    explanation: "姿态估计检测人体关节点（头、肩、肘、腕等）的位置，用于运动分析、健身指导、手势控制、舞蹈教学等应用。",
    reward: 5,
    isActive: true,
  },

  // ===== AI前沿进展 =====
  {
    question: "多模态AI（Multimodal AI）是指什么？",
    optionA: "能够同时运行多个任务的AI",
    optionB: "能够处理和理解多种类型数据（文本、图像、音频等）的AI",
    optionC: "在多台服务器上运行的AI",
    optionD: "支持多种编程语言的AI",
    correctAnswer: "B" as const,
    explanation: "多模态AI能够同时理解和生成文本、图像、音频、视频等多种形式的数据，GPT-4V、Gemini Ultra等都是多模态模型的代表。",
    reward: 5,
    isActive: true,
  },
  {
    question: "GPT-4相比GPT-3.5的主要改进是什么？",
    optionA: "响应速度更快",
    optionB: "支持图像输入（多模态）、推理能力更强、更安全",
    optionC: "价格更低",
    optionD: "只能处理英文",
    correctAnswer: "B" as const,
    explanation: "GPT-4支持图像输入（多模态理解），在复杂推理、代码生成、专业知识等方面有显著提升，并通过RLHF改善了安全性。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Mixture of Experts（MoE，专家混合）架构的主要优势是什么？",
    optionA: "减少模型参数总量",
    optionB: "在保持大容量的同时，每次推理只激活部分参数，降低计算成本",
    optionC: "提高训练数据质量",
    optionD: "增加模型层数",
    correctAnswer: "B" as const,
    explanation: "MoE架构包含多个'专家'子网络，每次推理由路由器选择激活少数专家，在保持模型总容量的同时大幅降低推理计算量，Mixtral、GPT-4等采用此架构。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI的'涌现能力'（Emergent Abilities）是指什么？",
    optionA: "AI突然出现故障",
    optionB: "模型规模达到一定阈值后，突然出现在小模型中不存在的新能力",
    optionC: "AI能够自主学习新技能",
    optionD: "AI能够连接到互联网",
    correctAnswer: "B" as const,
    explanation: "涌现能力指随着模型规模（参数量、训练数据）增大，模型在某个阈值后突然获得在小模型中不存在的能力，如多步推理、代码生成等。",
    reward: 5,
    isActive: true,
  },
  {
    question: "上下文学习（In-Context Learning）是指什么？",
    optionA: "AI在特定场景中学习",
    optionB: "通过在提示词中提供示例，让模型无需更新参数就能完成新任务",
    optionC: "AI记住所有对话历史",
    optionD: "在线实时训练模型",
    correctAnswer: "B" as const,
    explanation: "上下文学习（ICL）是大模型的独特能力：在提示词中给出几个示例（Few-shot），模型就能理解任务模式并完成新输入，无需任何参数更新。",
    reward: 5,
    isActive: true,
  },

  // ===== AI基础设施 =====
  {
    question: "GPU在AI训练中的优势是什么？",
    optionA: "存储容量更大",
    optionB: "拥有大量并行计算核心，适合矩阵运算",
    optionC: "功耗更低",
    optionD: "价格更便宜",
    correctAnswer: "B" as const,
    explanation: "GPU拥有数千个计算核心，非常适合深度学习中大量并行的矩阵乘法运算，训练速度比CPU快数十至数百倍。",
    reward: 5,
    isActive: true,
  },
  {
    question: "NVIDIA在AI领域的核心产品是什么？",
    optionA: "CPU处理器",
    optionB: "GPU和CUDA并行计算平台",
    optionC: "内存芯片",
    optionD: "网络设备",
    correctAnswer: "B" as const,
    explanation: "NVIDIA的GPU（如A100、H100）和CUDA并行计算平台是AI训练的主流基础设施，占据AI芯片市场的主导地位。",
    reward: 5,
    isActive: true,
  },
  {
    question: "模型推理（Inference）与模型训练（Training）的主要区别是什么？",
    optionA: "推理需要更多数据",
    optionB: "训练更新模型参数，推理使用固定参数对新数据进行预测",
    optionC: "推理需要更强的GPU",
    optionD: "两者完全相同",
    correctAnswer: "B" as const,
    explanation: "训练阶段通过反向传播不断更新模型参数；推理阶段使用训练好的固定参数对新输入进行预测，推理通常比训练计算量小得多。",
    reward: 5,
    isActive: true,
  },
  {
    question: "分布式训练（Distributed Training）的主要目的是什么？",
    optionA: "降低模型精度",
    optionB: "将训练任务分散到多台机器/GPU上，加速大模型训练",
    optionC: "减少训练数据",
    optionD: "简化模型结构",
    correctAnswer: "B" as const,
    explanation: "大模型训练需要巨大算力，分布式训练将计算任务分配到多台机器的多个GPU上并行执行，将训练时间从数年压缩到数周。",
    reward: 5,
    isActive: true,
  },
  {
    question: "模型即服务（Model as a Service，MaaS）的含义是什么？",
    optionA: "出售AI模型的源代码",
    optionB: "通过API提供AI模型的调用服务，无需用户自行部署",
    optionC: "提供AI模型的培训课程",
    optionD: "出租GPU服务器",
    correctAnswer: "B" as const,
    explanation: "MaaS是云服务模式，用户通过API调用OpenAI、Anthropic等公司的大模型，无需自行训练和部署，按调用量付费，大幅降低AI应用门槛。",
    reward: 5,
    isActive: true,
  },

  // ===== AI与数据 =====
  {
    question: "特征工程（Feature Engineering）在机器学习中的重要性是什么？",
    optionA: "不重要，深度学习可以自动提取特征",
    optionB: "对传统机器学习至关重要，好的特征能显著提升模型性能",
    optionC: "只用于图像处理",
    optionD: "只用于文本处理",
    correctAnswer: "B" as const,
    explanation: "特征工程是将原始数据转换为有意义特征的过程，对传统机器学习（随机森林、SVM等）影响巨大。虽然深度学习能自动学习特征，但领域知识驱动的特征工程仍有价值。",
    reward: 5,
    isActive: true,
  },
  {
    question: "数据清洗（Data Cleaning）在AI项目中的重要性是什么？",
    optionA: "不重要，AI可以处理任何质量的数据",
    optionB: "非常重要，'垃圾进，垃圾出'，数据质量直接决定模型质量",
    optionC: "只需要清洗一次",
    optionD: "只对图像数据重要",
    correctAnswer: "B" as const,
    explanation: "'Garbage In, Garbage Out'是AI领域的铁律，数据质量是模型性能的上限。数据清洗（处理缺失值、异常值、重复数据等）是AI项目中最耗时但最关键的步骤。",
    reward: 5,
    isActive: true,
  },
  {
    question: "A/B测试在AI产品中的主要用途是什么？",
    optionA: "测试AI模型的代码错误",
    optionB: "对比两个版本的效果，用数据驱动产品决策",
    optionC: "测试服务器性能",
    optionD: "测试用户界面颜色",
    correctAnswer: "B" as const,
    explanation: "A/B测试将用户随机分为两组，分别使用不同版本（如不同推荐算法），通过统计分析确定哪个版本效果更好，是数据驱动决策的核心方法。",
    reward: 5,
    isActive: true,
  },
  {
    question: "数据标注（Data Labeling）在监督学习中的作用是什么？",
    optionA: "给数据添加颜色",
    optionB: "为训练数据提供正确答案（标签），是监督学习的基础",
    optionC: "压缩数据大小",
    optionD: "加密数据",
    correctAnswer: "B" as const,
    explanation: "数据标注是为原始数据（图像、文本、音频等）添加正确标签的过程，是监督学习的必要前提，也是AI项目中成本最高的环节之一。",
    reward: 5,
    isActive: true,
  },
  {
    question: "合成数据（Synthetic Data）在AI训练中的主要用途是什么？",
    optionA: "替代所有真实数据",
    optionB: "在真实数据不足或敏感时，用算法生成模拟数据来补充训练集",
    optionC: "加速模型推理",
    optionD: "减少模型参数",
    correctAnswer: "B" as const,
    explanation: "合成数据通过仿真、GAN等技术生成，可以解决真实数据稀缺（如罕见疾病）、隐私敏感（如医疗数据）等问题，是AI数据策略的重要补充。",
    reward: 5,
    isActive: true,
  },

  // ===== AI与行业应用 =====
  {
    question: "AI在金融领域的主要应用不包括哪项？",
    optionA: "信用评分和风险控制",
    optionB: "量化交易策略",
    optionC: "欺诈检测",
    optionD: "替代央行制定货币政策",
    correctAnswer: "D" as const,
    explanation: "AI在金融领域广泛应用于信用评分、量化交易、欺诈检测、客服等，但货币政策等重大决策仍需人类决策者负责，AI只能提供辅助分析。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI在教育领域的主要应用是什么？",
    optionA: "完全替代教师",
    optionB: "个性化学习路径、智能辅导、自动批改作业",
    optionC: "只用于考试监控",
    optionD: "只用于行政管理",
    correctAnswer: "B" as const,
    explanation: "AI在教育中主要用于个性化学习（根据学生水平调整内容）、智能辅导系统、自动批改、学习分析等，目标是辅助教师而非替代。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI在农业中的'精准农业'应用包括什么？",
    optionA: "只用于销售农产品",
    optionB: "通过传感器和AI分析土壤、气候、作物状态，优化灌溉施肥",
    optionC: "替代所有农业劳动力",
    optionD: "只用于仓储管理",
    correctAnswer: "B" as const,
    explanation: "精准农业利用无人机、传感器收集数据，AI分析土壤湿度、作物健康、病虫害等，实现精准灌溉、施肥、喷药，提高产量同时减少资源浪费。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI在网络安全中的主要应用是什么？",
    optionA: "只用于防火墙配置",
    optionB: "异常流量检测、恶意软件识别、威胁情报分析",
    optionC: "替代所有安全人员",
    optionD: "只用于密码管理",
    correctAnswer: "B" as const,
    explanation: "AI在网络安全中用于实时检测异常网络行为、识别新型恶意软件、分析威胁情报，能够处理人工无法应对的海量安全事件。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI在人力资源领域的应用不包括哪项？",
    optionA: "简历筛选和候选人匹配",
    optionB: "员工绩效分析",
    optionC: "替代HR做所有录用决定",
    optionD: "员工培训个性化推荐",
    correctAnswer: "C" as const,
    explanation: "AI可以辅助HR进行简历筛选、绩效分析、培训推荐等，但最终录用决定涉及复杂的人际判断和法律责任，应由人类HR负责，AI只是辅助工具。",
    reward: 5,
    isActive: true,
  },

  // ===== AI工具与平台 =====
  {
    question: "Hugging Face平台在AI社区中的主要作用是什么？",
    optionA: "提供GPU租赁服务",
    optionB: "开源AI模型、数据集和工具的共享平台",
    optionC: "AI绘画平台",
    optionD: "AI游戏开发平台",
    correctAnswer: "B" as const,
    explanation: "Hugging Face是AI领域最重要的开源社区，提供数十万个预训练模型、数据集和Transformers等工具库，被称为'AI界的GitHub'。",
    reward: 5,
    isActive: true,
  },
  {
    question: "PyTorch和TensorFlow是什么？",
    optionA: "AI芯片品牌",
    optionB: "深度学习框架",
    optionC: "云计算平台",
    optionD: "数据库系统",
    correctAnswer: "B" as const,
    explanation: "PyTorch（Meta开发）和TensorFlow（Google开发）是最主流的深度学习框架，提供自动微分、GPU加速等功能，是AI研究和工程的基础工具。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AutoML（自动机器学习）的主要目标是什么？",
    optionA: "自动购买GPU",
    optionB: "自动化机器学习流程，让非专家也能构建AI模型",
    optionC: "自动生成训练数据",
    optionD: "自动部署AI到生产环境",
    correctAnswer: "B" as const,
    explanation: "AutoML自动化特征工程、模型选择、超参数调优等流程，降低AI应用门槛，让业务人员无需深度学习专业知识也能构建有效模型。",
    reward: 5,
    isActive: true,
  },
  {
    question: "MLOps的主要目标是什么？",
    optionA: "机器学习模型的销售",
    optionB: "将DevOps实践应用于机器学习，实现模型的持续集成、部署和监控",
    optionC: "优化机器学习算法",
    optionD: "管理机器学习团队",
    correctAnswer: "B" as const,
    explanation: "MLOps将软件工程的DevOps实践引入机器学习，解决模型版本管理、持续训练、自动部署、性能监控等工程挑战，确保AI系统在生产环境中稳定运行。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Jupyter Notebook在AI开发中的主要用途是什么？",
    optionA: "部署AI模型",
    optionB: "交互式数据分析和模型开发环境",
    optionC: "训练大型语言模型",
    optionD: "管理AI项目代码",
    correctAnswer: "B" as const,
    explanation: "Jupyter Notebook提供交互式编程环境，可以混合代码、可视化和文档，是数据科学家和AI研究者进行探索性分析和实验的首选工具。",
    reward: 5,
    isActive: true,
  },

  // ===== AI与未来 =====
  {
    question: "通用人工智能（AGI）与当前AI的主要区别是什么？",
    optionA: "AGI运行速度更快",
    optionB: "AGI能够像人类一样在任意领域执行智能任务，而非专注于特定任务",
    optionC: "AGI不需要训练数据",
    optionD: "AGI只能处理文本",
    correctAnswer: "B" as const,
    explanation: "当前AI是'窄AI'，只能在特定任务上表现优秀；AGI是假设中能够在任何智力任务上达到人类水平的AI，目前尚未实现，是AI研究的终极目标之一。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI对就业市场的影响，以下哪种观点最为准确？",
    optionA: "AI将消灭所有工作",
    optionB: "AI将替代部分重复性工作，同时创造新的工作机会，需要人类适应转型",
    optionC: "AI对就业没有任何影响",
    optionD: "AI只会影响体力劳动",
    correctAnswer: "B" as const,
    explanation: "历史上每次技术革命都改变了就业结构，AI也不例外。AI会替代重复性、规则性工作，但也会创造AI训练师、提示词工程师等新职业，关键是持续学习和适应。",
    reward: 5,
    isActive: true,
  },
  {
    question: "量子计算对AI的潜在影响是什么？",
    optionA: "量子计算与AI无关",
    optionB: "量子计算可能大幅加速特定AI算法，解决经典计算机难以处理的优化问题",
    optionC: "量子计算会取代所有AI",
    optionD: "量子计算只用于密码学",
    correctAnswer: "B" as const,
    explanation: "量子计算在特定算法（如量子机器学习、组合优化）上具有指数级加速潜力，可能推动AI在药物发现、材料科学、金融优化等领域的突破。",
    reward: 5,
    isActive: true,
  },
  {
    question: "神经形态计算（Neuromorphic Computing）的灵感来源是什么？",
    optionA: "量子力学",
    optionB: "模仿人脑神经元的工作方式设计芯片",
    optionC: "传统冯·诺依曼架构",
    optionD: "光学计算",
    correctAnswer: "B" as const,
    explanation: "神经形态计算模仿大脑神经元和突触的工作原理设计芯片（如Intel的Loihi），具有极低功耗和高并行性，是未来AI芯片的重要方向。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI冬天（AI Winter）是指什么？",
    optionA: "AI系统在冬季性能下降",
    optionB: "AI研究和投资大幅减少的低谷时期",
    optionC: "AI无法处理冬季数据",
    optionD: "AI研究人员的休假期",
    correctAnswer: "B" as const,
    explanation: "AI历史上经历过两次'AI冬天'（1970s和1980s-90s），因技术瓶颈导致研究热情和投资骤降。了解历史有助于理性看待当前AI热潮。",
    reward: 5,
    isActive: true,
  },

  // ===== 实践与应用技巧 =====
  {
    question: "在使用ChatGPT等大模型时，如何获得更准确的回答？",
    optionA: "尽量使用简短的问题",
    optionB: "提供清晰的背景信息、明确的要求和具体的输出格式",
    optionC: "重复提问多次",
    optionD: "使用专业术语越多越好",
    correctAnswer: "B" as const,
    explanation: "高质量的提示词应包含：背景信息（你是谁、场景是什么）、明确的任务要求、期望的输出格式，以及必要的约束条件，这样能显著提升回答质量。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI生成内容（AIGC）在工作中使用时，最重要的注意事项是什么？",
    optionA: "直接使用，不需要验证",
    optionB: "需要人工审核验证，不能盲目信任AI输出",
    optionC: "只能用于娱乐",
    optionD: "必须告诉所有人内容是AI生成的",
    correctAnswer: "B" as const,
    explanation: "AI可能产生幻觉（生成错误信息），在工作中使用AIGC时必须进行事实核查和质量审核，尤其是涉及数据、法律、医疗等专业领域时。",
    reward: 5,
    isActive: true,
  },
  {
    question: "企业部署AI时，数据安全的主要考虑是什么？",
    optionA: "只需要防止外部攻击",
    optionB: "敏感数据不应上传到第三方AI服务，需要评估数据隐私风险",
    optionC: "AI自动保护所有数据",
    optionD: "数据安全与AI无关",
    correctAnswer: "B" as const,
    explanation: "使用第三方AI API时，输入的数据可能被服务商用于模型训练，企业应评估数据敏感性，对于商业机密、个人信息等应使用私有化部署或数据脱敏。",
    reward: 5,
    isActive: true,
  },
  {
    question: "评估AI模型性能时，准确率（Accuracy）是否总是最重要的指标？",
    optionA: "是的，准确率是唯一重要的指标",
    optionB: "不是，在类别不平衡或不同错误成本不同时，需要用精确率、召回率、F1等综合评估",
    optionC: "不是，速度比准确率更重要",
    optionD: "准确率不重要",
    correctAnswer: "B" as const,
    explanation: "在医疗诊断（漏诊代价远高于误诊）、欺诈检测（正负样本极度不平衡）等场景，单纯追求准确率会误导评估，需要根据业务场景选择合适的评估指标。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI项目失败的最常见原因是什么？",
    optionA: "算法选择错误",
    optionB: "数据质量差、目标不清晰、缺乏业务整合",
    optionC: "GPU性能不足",
    optionD: "团队规模太小",
    correctAnswer: "B" as const,
    explanation: "AI项目失败最常见的原因不是技术问题，而是：数据质量和数量不足、业务目标不明确、AI结果无法融入实际工作流程、缺乏持续维护等非技术因素。",
    reward: 5,
    isActive: true,
  },

  // ===== 前沿研究方向 =====
  {
    question: "联邦学习（Federated Learning）的主要优势是什么？",
    optionA: "训练速度更快",
    optionB: "数据留在本地，保护隐私的同时实现多方协作训练",
    optionC: "模型精度更高",
    optionD: "不需要GPU",
    correctAnswer: "B" as const,
    explanation: "联邦学习让各参与方在本地训练模型，只共享模型梯度而非原始数据，解决了医疗、金融等敏感领域的数据孤岛和隐私保护问题。",
    reward: 5,
    isActive: true,
  },
  {
    question: "神经架构搜索（NAS）的目标是什么？",
    optionA: "搜索互联网上的神经网络资料",
    optionB: "自动搜索最优的神经网络架构，替代人工设计",
    optionC: "优化神经网络的权重",
    optionD: "压缩神经网络模型",
    correctAnswer: "B" as const,
    explanation: "NAS使用算法自动搜索最优的网络结构（层数、连接方式、激活函数等），减少人工设计的工作量，已发现了多个超越人工设计的高效架构。",
    reward: 5,
    isActive: true,
  },
  {
    question: "持续学习（Continual Learning）要解决的核心问题是什么？",
    optionA: "让AI学得更快",
    optionB: "让AI在学习新任务时不遗忘旧知识（灾难性遗忘问题）",
    optionC: "让AI持续运行不停机",
    optionD: "让AI自动更新软件",
    correctAnswer: "B" as const,
    explanation: "当前AI在学习新任务时会'遗忘'旧任务（灾难性遗忘），持续学习研究如何让AI像人类一样持续积累知识，是迈向AGI的重要研究方向。",
    reward: 5,
    isActive: true,
  },
  {
    question: "因果推断（Causal Inference）在AI中的重要性是什么？",
    optionA: "不重要，相关性就足够了",
    optionB: "帮助AI理解因果关系而非仅仅相关性，提高决策可靠性",
    optionC: "只用于医学研究",
    optionD: "只用于金融分析",
    correctAnswer: "B" as const,
    explanation: "'相关不等于因果'，当前AI擅长发现相关性但难以理解因果关系。因果推断让AI能够回答'如果...会怎样'的反事实问题，对可靠决策至关重要。",
    reward: 5,
    isActive: true,
  },
  {
    question: "具身智能（Embodied AI）研究的核心是什么？",
    optionA: "让AI拥有身体外形",
    optionB: "让AI通过与物理环境的交互来学习和发展智能",
    optionC: "让AI控制人类身体",
    optionD: "让AI在虚拟现实中运行",
    correctAnswer: "B" as const,
    explanation: "具身智能认为真正的智能需要通过与物理世界的感知和交互来发展，研究让机器人、自动驾驶等系统通过实体交互学习，是AI与机器人学的交叉前沿。",
    reward: 5,
    isActive: true,
  },

  // ===== 补充题目（凑足200道）=====
  {
    question: "Zero-shot学习是指什么？",
    optionA: "不需要任何训练的AI",
    optionB: "模型在没有见过任何该类别示例的情况下完成任务",
    optionC: "只训练一次的模型",
    optionD: "零延迟的AI推理",
    correctAnswer: "B" as const,
    explanation: "Zero-shot学习指模型在推理时面对从未在训练数据中出现过的类别或任务，仍能做出合理预测，大语言模型在这方面表现出色。",
    reward: 5,
    isActive: true,
  },
  {
    question: "模型的'上下文窗口'（Context Window）是指什么？",
    optionA: "模型的界面窗口大小",
    optionB: "模型一次能处理的最大文本长度（以Token计）",
    optionC: "模型的训练数据时间范围",
    optionD: "模型的响应时间",
    correctAnswer: "B" as const,
    explanation: "上下文窗口是LLM一次能处理的最大输入长度，GPT-4的上下文窗口达128K Token，更大的窗口允许处理更长的文档和对话历史。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI幻觉（Hallucination）最有效的缓解方法是什么？",
    optionA: "使用更大的模型",
    optionB: "RAG（检索增强生成）+ 人工验证",
    optionC: "增加训练数据",
    optionD: "提高模型温度参数",
    correctAnswer: "B" as const,
    explanation: "RAG通过检索可信知识库来约束模型输出，是目前最有效的减少幻觉方法之一；同时对重要输出进行人工验证是工程实践中不可缺少的环节。",
    reward: 5,
    isActive: true,
  },
  {
    question: "什么是'温度'（Temperature）参数在LLM中的作用？",
    optionA: "控制模型运行时的CPU温度",
    optionB: "控制输出的随机性，温度越高输出越多样，越低越确定",
    optionC: "控制模型的训练速度",
    optionD: "控制输出文本的长度",
    correctAnswer: "B" as const,
    explanation: "Temperature参数控制LLM输出的随机性：温度接近0时输出最确定（适合事实性问答），温度高时输出更多样创意（适合创意写作）。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪个是AI生成内容检测工具的主要挑战？",
    optionA: "检测工具太贵",
    optionB: "随着生成模型改进，检测准确率难以保持，存在误判风险",
    optionC: "检测速度太慢",
    optionD: "检测工具只能检测英文",
    correctAnswer: "B" as const,
    explanation: "AI内容检测是'矛与盾'的博弈，随着生成模型不断进步，检测工具的准确率持续下降，且存在将人类写作误判为AI的风险，不能作为唯一判断依据。",
    reward: 5,
    isActive: true,
  },
  {
    question: "Sora（OpenAI视频生成模型）的主要技术创新是什么？",
    optionA: "使用GAN生成视频",
    optionB: "将扩散模型与Transformer结合，能生成长达60秒的高质量视频",
    optionC: "使用RNN处理视频序列",
    optionD: "通过拼接真实视频片段",
    correctAnswer: "B" as const,
    explanation: "Sora将扩散Transformer（DiT）应用于视频生成，能够生成高度一致、物理规律合理的长视频，代表了AI视频生成的重大突破。",
    reward: 5,
    isActive: true,
  },
  {
    question: "AI在代码生成方面，以下哪种说法最准确？",
    optionA: "AI可以完全替代程序员",
    optionB: "AI能显著提升开发效率，但生成的代码需要人工审查和测试",
    optionC: "AI只能生成简单的代码片段",
    optionD: "AI生成的代码总是正确的",
    correctAnswer: "B" as const,
    explanation: "AI代码生成工具（Copilot、Cursor等）能大幅提升开发效率，但生成的代码可能存在逻辑错误、安全漏洞，必须经过人工审查、测试才能用于生产环境。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪个概念描述了AI模型在部署后性能逐渐下降的现象？",
    optionA: "模型崩溃",
    optionB: "模型漂移（Model Drift）",
    optionC: "模型过拟合",
    optionD: "模型欠拟合",
    correctAnswer: "B" as const,
    explanation: "模型漂移指生产环境中数据分布随时间变化，导致模型性能下降。需要持续监控模型指标，定期用新数据重新训练，这是MLOps的核心任务之一。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪个是开源的本地部署大语言模型？",
    optionA: "GPT-4",
    optionB: "Claude 3",
    optionC: "Ollama（支持运行Llama、Mistral等开源模型）",
    optionD: "Gemini Ultra",
    correctAnswer: "C" as const,
    explanation: "Ollama是开源工具，允许用户在本地计算机上运行Llama、Mistral、Gemma等开源大模型，无需联网，保护数据隐私，适合企业私有化部署。",
    reward: 5,
    isActive: true,
  },
  {
    question: "以下哪个说法正确描述了当前AI的局限性？",
    optionA: "AI已经完全理解人类语言和意图",
    optionB: "AI缺乏真正的理解和常识，在分布外数据上容易失败",
    optionC: "AI可以处理任何问题",
    optionD: "AI的判断总是比人类更准确",
    correctAnswer: "B" as const,
    explanation: "当前AI（包括大语言模型）本质上是统计模式匹配，缺乏真正的理解、常识推理和因果思维，在训练数据覆盖不到的情况下容易产生错误，需要人类监督。",
    reward: 5,
    isActive: true,
  },
];
